export { CatchPhraseText } from './CatchPhraseText/CatchPhraseText';
export { DescriptionAppText } from './DescriptionAppText/DescriptionAppText';
export { HeaderTitleText } from './HeaderTitleText/HeaderTitleText';
export { FooterApiText } from './FooterApiText/FooterApiText';
export { FooterAuthorText } from './FooterAuthorText/FooterAuthorText';
export { FooterImageUrlText } from './FooterImageUrlText/FooterImageUrlText';
export { HeaderLoginText } from './HeaderLoginText/HeaderLoginText';
export { HeaderQuestionIcon } from './HeaderQuestionIcon/HeaderQuestionIcon';
export { ModalCloseIcon } from './ModalCloseIcon/ModalCloseIcon';